### ISSUE TITLE
无法获取资源详情页

### ISSUE THREAD

**Issue by gramce** [ingbyr/GUI-YouGet#31]
2018-01-16 00:29:40.232 [JavaFX Application Thread] DEBUG com.ingbyr.guiyouget.Main.<init>(16) - OS: Windows 10 Arch: amd64 Version: 10.0
2018-01-16 00:29:40.234 [JavaFX Application Thread] DEBUG com.ingbyr.guiyouget.Main.<init>(17) - JAVA: 1.8.0_151 Vender: Oracle Corporation
2018-01-16 00:29:40.234 [JavaFX Application Thread] DEBUG com.ingbyr.guiyouget.Main.<init>(18) - Default locale: zh_CN
2018-01-16 00:29:42.391 [JavaFX Application Thread] DEBUG c.i.g.controllers.MainController.requestMediaInfo(18) - download core is youtube-dl
2018-01-16 00:29:42.395 [Thread-5] DEBUG com.ingbyr.guiyouget.core.CoreArgs.build(25) - run command [E:\gui-you-get\core\youtube-dl.exe, -j, https://www.bilibili.com/video/av18272782/?spm_id_from=333.334.home_popularize.3]
2018-01-16 00:29:42.396 [Thread-5] ERROR c.i.g.c.MediaListController.invoke(32) - java.io.IOException: Cannot run program "E:\gui-you-get\core\youtube-dl.exe": CreateProcess error=193, %1 不是有效的 Win32 应用程序。
2018-01-16 00:30:12.298 [JavaFX Application Thread] DEBUG c.i.g.controllers.MainController.requestMediaInfo(18) - download core is you-get
2018-01-16 00:30:12.300 [Thread-6] DEBUG com.ingbyr.guiyouget.core.CoreArgs.build(25) - run command [E:\gui-you-get\core\you-get.exe, --json, https://www.bilibili.com/video/av18272782/?spm_id_from=333.334.home_popularize.3]
2018-01-16 00:30:13.498 [Thread-6] ERROR c.i.g.c.MediaListController.invoke(44) - java.lang.RuntimeException: Unexpected character at position 2: 'y (121)'

**Comment by ingbyr** [comment]
应该是 [you-get](https://github.com/soimort/you-get) 的BUG

```
/tmp> you-get -i "https://www.bilibili.com/video/av18272782/?spm_id_from=333.334.home_popularize.3" --debug
[DEBUG] url_locations: https://www.bilibili.com/video/av18272782/?spm_id_from=333.334.home_popularize.3
[DEBUG] get_content: https://www.bilibili.com/video/av18272782/?spm_id_from=333.334.home_popularize.3
[DEBUG] get_content: http://interface.bilibili.com/playurl?cid=29829279&player=1&quality=4&ts=1516087633&sign=67499c565f6a4a17dda1e7099cd76ffe
[DEBUG] HTTP Error with code403
[DEBUG] HTTP Error with code403
[DEBUG] HTTP Error with code403
you-get: version 0.4.1011, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['https://www.bilibili.com/video/av18272782/?spm_id_from=333.334.home_popularize.3'], cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=True, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "/home/ing/.local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/home/ing/.local/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/home/ing/.local/lib/python3.5/site-packages/you_get/common.py", line 1583, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "/home/ing/.local/lib/python3.5/site-packages/you_get/common.py", line 1472, in script_main
    **extra
  File "/home/ing/.local/lib/python3.5/site-packages/you_get/common.py", line 1216, in download_main
    download(url, **kwargs)
  File "/home/ing/.local/lib/python3.5/site-packages/you_get/common.py", line 1574, in any_download
    m.download(url, **kwargs)
  File "/home/ing/.local/lib/python3.5/site-packages/you_get/extractor.py", line 46, in download_by_url
    self.prepare(**kwargs)
  File "/home/ing/.local/lib/python3.5/site-packages/you_get/extractors/bilibili.py", line 148, in prepare
    self.entry(**kwargs)
  File "/home/ing/.local/lib/python3.5/site-packages/you_get/extractors/bilibili.py", line 173, in entry
    self.download_by_vid(cid, False, **kwargs)
  File "/home/ing/.local/lib/python3.5/site-packages/you_get/extractors/bilibili.py", line 101, in download_by_vid
    api_xml = self.api_req(cid, qlt, bangumi, **kwargs)
  File "/home/ing/.local/lib/python3.5/site-packages/you_get/extractors/bilibili.py", line 71, in api_req
    xml_str = get_content(api_url)
  File "/home/ing/.local/lib/python3.5/site-packages/you_get/common.py", line 413, in get_content
    response = urlopen_with_retry(req)
  File "/home/ing/.local/lib/python3.5/site-packages/you_get/common.py", line 391, in urlopen_with_retry
    raise http_error
  File "/home/ing/.local/lib/python3.5/site-packages/you_get/common.py", line 382, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by gramce** [comment]
是不是bilibili上了反抓取

**Comment by gramce** [comment]
youku bilibili 貌似都挂了

**Comment by gramce** [comment]
加header 随机sleep一下 可以过
等you-get更新啊吧
