### ISSUE TITLE
无法打开软件

### ISSUE THREAD

**Issue by Cwinsan** [ingbyr/GUI-YouGet#34]
弹出一个框里面是这样的：
kotlin.TypeCastException: null cannot be cast to non-null type kotlin.String
	at com.ingbyr.guiyouget.views.MainView.<init>(MainView.kt:139)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at tornadofx.FXKt.find(FX.kt:401)
	at tornadofx.FXKt.find$default(FX.kt:387)
	at tornadofx.App.start(App.kt:79)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Unknown Source)

**Comment by ingbyr** [comment]
是否手动修改过app.properties中的version？

**Comment by Rictusempra** [comment]
最新一个版本在最新版本的win 10安装之后也是无法运行
但是仅提示程序已停止运行。。

**Comment by ingbyr** [comment]
@Rictusempra 可否发一下log内容

**Comment by Rictusempra** [comment]
但是搜索安装目录并未发现含 log 这个关键词的文本文件。。。

**Comment by gn80797** [comment]
![image](https://user-images.githubusercontent.com/36289217/36012128-fe31cedc-0d96-11e8-8947-77ed072d11d4.png)

LOG
2018-02-09 12:40:41.598 [JavaFX Application Thread] DEBUG com.ingbyr.guiyouget.Main.<init>(16) - OS: Windows 10 Arch: x86 Version: 10.0
2018-02-09 12:40:41.601 [JavaFX Application Thread] DEBUG com.ingbyr.guiyouget.Main.<init>(17) - JAVA: 1.8.0_161 Vender: Oracle Corporation
2018-02-09 12:40:41.601 [JavaFX Application Thread] DEBUG com.ingbyr.guiyouget.Main.<init>(18) - Default locale: zh_TW
