### ISSUE TITLE
自动更新youget代码库

### ISSUE THREAD

**Issue by Rictusempra** [ingbyr/GUI-YouGet#7]
与其youget每次都更新都打包 不如添加更新库的功能

**Comment by kumakichi** [comment]
我用bash做了实验，将界面和you-get分离，可以用了

如果你也用bash和GNU tools，可以试试:

https://github.com/kumakichi/gui-you-get

**Comment by Hello-everybody** [comment]
解析网易云音乐出错  代码贴上:
May23 2017 11:34:47 main_window.py[line:76] DEBUG >>> http://music.163.com/#/mv?id=28207
May23 2017 11:34:47 download_thread.py[line:37] DEBUG >>> enable socks proxy
May23 2017 11:34:47 common.py[line:345] DEBUG >>> get_content: http://music.163.com/api/mv/detail/?id=28207&ids=[28207]&csrf_token=
May23 2017 11:34:49 download_thread.py[line:49] ERROR >>> <urlopen error Error connecting to SOCKS5 proxy 127.0.0.1:1080: [WinError 10061] 由于目标计算机积极拒绝，无法连接。>
Traceback (most recent call last):
  File "site-packages\socks.py", line 765, in connect
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib\request.py", line 1254, in do_open
  File "http\client.py", line 1106, in request
  File "http\client.py", line 1151, in _send_request
  File "http\client.py", line 1102, in endheaders
  File "http\client.py", line 934, in _send_output
  File "http\client.py", line 877, in send
  File "http\client.py", line 849, in connect
  File "socket.py", line 711, in create_connection
  File "socket.py", line 702, in create_connection
  File "site-packages\socks.py", line 776, in connect
socks.ProxyConnectionError: Error connecting to SOCKS5 proxy 127.0.0.1:1080: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app\util\download_thread.py", line 45, in run
  File "app\you_get\common.py", line 1202, in download_main
  File "app\you_get\common.py", line 1470, in any_download
  File "app\you_get\extractors\netease.py", line 133, in netease_download
  File "app\you_get\extractors\netease.py", line 87, in netease_cloud_music_download
  File "app\you_get\common.py", line 352, in get_content
  File "app\you_get\common.py", line 328, in urlopen_with_retry
  File "urllib\request.py", line 163, in urlopen
  File "urllib\request.py", line 466, in open
  File "urllib\request.py", line 484, in _open
  File "urllib\request.py", line 444, in _call_chain
  File "urllib\request.py", line 1282, in http_open
  File "urllib\request.py", line 1256, in do_open
urllib.error.URLError: <urlopen error Error connecting to SOCKS5 proxy 127.0.0.1:1080: [WinError 10061] 由于目标计算机积极拒绝，无法连接。>
May23 2017 11:34:49 main_window.py[line:83] DEBUG >>> finish_get_info: False
May23 2017 11:35:07 main_window.py[line:128] ERROR >>> <urlopen error Error connecting to SOCKS5 proxy 127.0.0.1:1080: [WinError 10061] 由于目标计算机积极拒绝，无法连接。>
Traceback (most recent call last):
  File "site-packages\socks.py", line 765, in connect
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

**Comment by kumakichi** [comment]
@Hello-everybody 

> socks.ProxyConnectionError: Error connecting to SOCKS5 proxy 127.0.0.1:1080: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

**Comment by Hello-everybody** [comment]
@kumakichi  那应该怎样修改  或者怎么解决

**Comment by kumakichi** [comment]
@Hello-everybody 

禁用代理

**Comment by ingbyr** [comment]
[0.2版本](https://github.com/ingbyr/GUI-YouGet/releases) 实现了多内核和自动更新
